import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { AlertsProvider } from "@/contexts/alerts-context"
import { Suspense } from "react"
import { RecentkyViwedProductsProvider } from "@/contexts/recently-viewed-products-list-context"

const mainLocalFontFamily = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-family-main",
})

export const metadata: Metadata = {
  title: "Hardware Price Tracker",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${mainLocalFontFamily.variable} antialiased`}>
        <Suspense>
          <AlertsProvider>
            <RecentkyViwedProductsProvider>
              {children}
            </RecentkyViwedProductsProvider>
          </AlertsProvider>

          <Toaster />
        </Suspense>
      </body>
    </html>
  )
}
